### ISSUE TITLE
Cannot run skin appTemp not in DB

### ISSUE THREAD

**Issue by glenosAU** [dcapslock/weewx-responsive-skin#10]
I've tried to apply this skin to my existing default install and have hit a wall. I am sure it is not too dificult, but I cannot figure out what I am missing. With your skin set to run in weewx.conf when I try to generate reports I get the following:

> root@pi:/var/lib/weewx# wee_reports /etc/weewx/weewx.conf
Using configuration file /etc/weewx/weewx.conf
Generating for all time
Traceback (most recent call last):
  File "/usr/share/weewx/weewx/reportengine.py", line 204, in run obj.start()
  File "/usr/share/weewx/weewx/reportengine.py", line 300, in start self.run()
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 157, in run self.initExtensions(gen_dict[section_name])
  File "/usr/share/weewx/weewx/cheetahgenerator.py", line 199, in initExtensions class_ = weeutil.weeutil._get_object(x)
  File "/usr/share/weewx/weeutil/weeutil.py", line 1107, in _get_object mod = __import__(module)
  File "/usr/share/weewx/user/aussearch.py", line 2, in <module> import pytz
ImportError: No module named pytz
Traceback (most recent call last):
  File "/usr/share/weewx/weewx/reportengine.py", line 204, in run obj.start()
  File "/usr/share/weewx/weewx/reportengine.py", line 300, in start self.run()
  File "/usr/share/weewx/weewx/imagegenerator.py", line 33, in run self.genImages(self.gen_ts)
  File "/usr/share/weewx/weewx/imagegenerator.py", line 170, in genImages aggregate_interval=aggregate_interval)
  File "/usr/share/weewx/weewx/manager.py", line 513, in getSqlVectors aggregate_type, aggregate_interval)
  File "/usr/share/weewx/weewx/manager.py", line 790, in _getSqlVectors for _rec in _cursor.execute(sql_str, (startstamp, stopstamp)):
  File "/usr/share/weewx/weedb/sqlite.py", line 41, in guarded_fn raise weedb.NoColumnError(e)
NoColumnError: no such column: appTemp

I assume this means I need to add appTemp to the database schema, but I cannot figure how to do it. I tried to understand the wiki but I don't get it.

Are you able to offer any help?

**Comment by dcapslock** [comment]
Hi There,

Yes, appTemp required. See general weeex guide on updating schema. https://github.com/poblabs/weewx-belchertown/wiki/Adding-a-new-observation-type-to-the-WeeWX-database

Cheers

Darryn

________________________________

**Comment by glenosAU** [comment]
Thanks Darryn,
Got it working. Strated the day as a clean up of bad data due to a shaking rain bucket, ended up with a new skin. I did have a problem running the rports initially, index.html.tmpl would not run. There was an error about dateutils.parser module not found.

Next trick is to get ET and GDD calculated, I only have a WH1080 so need to assume solar radiation for ET an approximate ET will do its for irrigation scheduling on a farm.

Cheers
Glen
