### ISSUE TITLE
Report crashes

### ISSUE THREAD

**Issue by tkontogi** [dcapslock/weewx-responsive-skin#6]
Hello,

CEntOS 7.3 with weewx 3.7.0
Download .zip via github webinterface.
unziped it under /etc/weewx/skins
Changed report skin to Responsive

I get

```
Mar 17 01:35:29 tweety weewx[31118]: reportengine: Caught unrecoverable exception in generator weewx.cheetahgenerator.CheetahGenerator
Mar 17 01:35:29 tweety weewx[31118]:        ****  No module named aussearch
Mar 17 01:35:29 tweety weewx[31118]:        ****  Traceback (most recent call last):
Mar 17 01:35:29 tweety weewx[31118]:        ****    File "/usr/share/weewx/weewx/reportengine.py", line 239, in run
Mar 17 01:35:29 tweety weewx[31118]:        ****      obj.start()
Mar 17 01:35:29 tweety weewx[31118]:        ****    File "/usr/share/weewx/weewx/reportengine.py", line 273, in start
Mar 17 01:35:29 tweety weewx[31118]:        ****      self.run()
Mar 17 01:35:29 tweety weewx[31118]:        ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 154, in run
Mar 17 01:35:29 tweety weewx[31118]:        ****      self.initExtensions(gen_dict[section_name])
Mar 17 01:35:29 tweety weewx[31118]:        ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 196, in initExtensions
Mar 17 01:35:29 tweety weewx[31118]:        ****      class_ = weeutil.weeutil._get_object(x)
Mar 17 01:35:29 tweety weewx[31118]:        ****    File "/usr/share/weewx/weeutil/weeutil.py", line 1132, in _get_object
Mar 17 01:35:29 tweety weewx[31118]:        ****      mod = __import__(module)
Mar 17 01:35:29 tweety weewx[31118]:        ****  ImportError: No module named aussearch
Mar 17 01:35:29 tweety weewx[31118]:        ****  Generator terminated
Mar 17 01:35:29 tweety weewx[31118]: reportengine: Caught unrecoverable exception in generator weewx.imagegenerator.ImageGenerator
Mar 17 01:35:29 tweety weewx[31118]:        ****  (1054, "Unknown column 'appTemp' in 'field list'")
Mar 17 01:35:29 tweety weewx[31118]:        ****  Traceback (most recent call last):
Mar 17 01:35:29 tweety weewx[31118]:        ****    File "/usr/share/weewx/weewx/reportengine.py", line 239, in run
Mar 17 01:35:29 tweety weewx[31118]:        ****      obj.start()
Mar 17 01:35:29 tweety weewx[31118]:        ****    File "/usr/share/weewx/weewx/reportengine.py", line 273, in start
Mar 17 01:35:29 tweety weewx[31118]:        ****      self.run()
Mar 17 01:35:29 tweety weewx[31118]:        ****    File "/usr/share/weewx/weewx/imagegenerator.py", line 31, in run
Mar 17 01:35:29 tweety weewx[31118]:        ****      self.genImages(self.gen_ts)
Mar 17 01:35:29 tweety weewx[31118]:        ****    File "/usr/share/weewx/weewx/imagegenerator.py", line 141, in genImages
Mar 17 01:35:29 tweety weewx[31118]:        ****      aggregate_interval=aggregate_interval)
Mar 17 01:35:29 tweety weewx[31118]:        ****    File "/usr/share/weewx/weewx/manager.py", line 511, in getSqlVectors
Mar 17 01:35:29 tweety weewx[31118]:        ****      aggregate_type, aggregate_interval)
Mar 17 01:35:29 tweety weewx[31118]:        ****    File "/usr/share/weewx/weewx/manager.py", line 757, in _getSqlVectors
Mar 17 01:35:29 tweety weewx[31118]:        ****      for _rec in _cursor.execute(sql_str, (startstamp, stopstamp)):
Mar 17 01:35:29 tweety weewx[31118]:        ****    File "/usr/share/weewx/weedb/mysql.py", line 46, in guarded_fn
Mar 17 01:35:29 tweety weewx[31118]:        ****      raise klass(e)
Mar 17 01:35:29 tweety weewx[31118]:        ****  NoColumnError: (1054, "Unknown column 'appTemp' in 'field list'")
Mar 17 01:35:29 tweety weewx[31118]:        ****  Generator terminated
Mar 17 01:35:29 tweety weewx[31118]: copygenerator: copied 3 files to /mnt/services/www/html/weewx
Mar 17 01:35:29 tweety weewx[31118]: reportengine: Caught unrecoverable exception in generator weewx.cheetahgenerator.CheetahGenerator
Mar 17 01:35:29 tweety weewx[31118]:        ****  No module named aussearch
Mar 17 01:35:29 tweety weewx[31118]:        ****  Traceback (most recent call last):
Mar 17 01:35:29 tweety weewx[31118]:        ****    File "/usr/share/weewx/weewx/reportengine.py", line 239, in run
Mar 17 01:35:29 tweety weewx[31118]:        ****      obj.start()
Mar 17 01:35:29 tweety weewx[31118]:        ****    File "/usr/share/weewx/weewx/reportengine.py", line 273, in start
Mar 17 01:35:29 tweety weewx[31118]:        ****      self.run()
Mar 17 01:35:29 tweety weewx[31118]:        ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 154, in run
Mar 17 01:35:29 tweety weewx[31118]:        ****      self.initExtensions(gen_dict[section_name])
Mar 17 01:35:29 tweety weewx[31118]:        ****    File "/usr/share/weewx/weewx/cheetahgenerator.py", line 196, in initExtensions
Mar 17 01:35:29 tweety weewx[31118]:        ****      class_ = weeutil.weeutil._get_object(x)
Mar 17 01:35:29 tweety weewx[31118]:        ****    File "/usr/share/weewx/weeutil/weeutil.py", line 1132, in _get_object
Mar 17 01:35:29 tweety weewx[31118]:        ****      mod = __import__(module)
Mar 17 01:35:29 tweety weewx[31118]:        ****  ImportError: No module named aussearch
Mar 17 01:35:29 tweety weewx[31118]:        ****  Generator terminated
Mar 17 01:35:29 tweety weewx[31118]: reportengine: Caught unrecoverable exception in generator weewx.imagegenerator.ImageGenerator
Mar 17 01:35:29 tweety weewx[31118]:        ****  (1054, "Unknown column 'appTemp' in 'field list'")
Mar 17 01:35:29 tweety weewx[31118]:        ****  Traceback (most recent call last):
Mar 17 01:35:29 tweety weewx[31118]:        ****    File "/usr/share/weewx/weewx/reportengine.py", line 239, in run
Mar 17 01:35:29 tweety weewx[31118]:        ****      obj.start()
Mar 17 01:35:29 tweety weewx[31118]:        ****    File "/usr/share/weewx/weewx/reportengine.py", line 273, in start
Mar 17 01:35:29 tweety weewx[31118]:        ****      self.run()
Mar 17 01:35:29 tweety weewx[31118]:        ****    File "/usr/share/weewx/weewx/imagegenerator.py", line 31, in run
Mar 17 01:35:29 tweety weewx[31118]:        ****      self.genImages(self.gen_ts)
Mar 17 01:35:29 tweety weewx[31118]:        ****    File "/usr/share/weewx/weewx/imagegenerator.py", line 141, in genImages
Mar 17 01:35:29 tweety weewx[31118]:        ****      aggregate_interval=aggregate_interval)
Mar 17 01:35:29 tweety weewx[31118]:        ****    File "/usr/share/weewx/weewx/manager.py", line 511, in getSqlVectors
Mar 17 01:35:29 tweety weewx[31118]:        ****      aggregate_type, aggregate_interval)
Mar 17 01:35:29 tweety weewx[31118]:        ****    File "/usr/share/weewx/weewx/manager.py", line 757, in _getSqlVectors
Mar 17 01:35:29 tweety weewx[31118]:        ****      for _rec in _cursor.execute(sql_str, (startstamp, stopstamp)):
Mar 17 01:35:29 tweety weewx[31118]:        ****    File "/usr/share/weewx/weedb/mysql.py", line 46, in guarded_fn
Mar 17 01:35:29 tweety weewx[31118]:        ****      raise klass(e)
Mar 17 01:35:29 tweety weewx[31118]:        ****  NoColumnError: (1054, "Unknown column 'appTemp' in 'field list'")
Mar 17 01:35:29 tweety weewx[31118]:        ****  Generator terminated
```
The comments mention aussearch extensions but how to get them?

FYI: This weewx is running in Europe.

Thank you

**Comment by dcapslock** [comment]
Hi there,

You will either need to include aussearch.py in your Weewx user folder see Aus code directory).

Regards

Darryn

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by tkontogi** [comment]
Hello,

I am completely ignorant of python so I do not know where to add the
include statement.

Could you kindly provide a working example or sample code/config file?

Kind regards,

Theo



---
Best regards,
ΜΦΧ,

Theophanis Kontogiannis

**Comment by dcapslock** [comment]
Hi there,

Follow the instructions at the top of the wiki page https://github.com/dcapslock/weewx-responsive-skin/wiki/Australian-%27Search%27-Extensions

Regards

Darryn


________________________________
